import type { Metadata } from "next";
import { Geist, Geist_Mono, Onest } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const pokeHollow = localFont({src:'../fonts/Hollow.ttf', variable:'--font-hollow'})
const pokeSolid = localFont({src:'../fonts/Solid.ttf', variable: '--font-solid'})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const onest = Onest({
  variable: "--font-gest-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Home- Pokecam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${pokeHollow.variable} ${pokeSolid.variable}`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
